/*
 *   ORXONOX - the hottest 3D action shooter ever to exist
 *                    > www.orxonox.net <
 *
 *
 *   License notice:
 *
 *   This program is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU General Public License
 *   as published by the Free Software Foundation; either version 2
 *   of the License, or (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 *   Author:
 *      Reto Grieder
 *   Co-authors:
 *      ...
 *
 */

// 5/9/2009: Adapted to the MAVCONN Project by Fabian Landau

/**
 @file
 @brief
    Various constants and options that only affect very little code.
 @note
    DO NOT EDIT THIS FILE!
    It has been automatically generated by CMake from MAVCONNConfig.h.in
 */

#ifndef _MAVCONNPathConfig_H__
#define _MAVCONNPathConfig_H__

#include "MAVCONNConfig.h"

/* MAVCONN either gets installed to the system or just into a folder.
   The latter uses relative paths. */
/* #undef INSTALL_COPYABLE */

/* Using MSVC or XCode IDE */
/* #undef CMAKE_CONFIGURATION_TYPES */

/* Handle default ConfigValues */
namespace MAVCONN
{
    const char* const MAVCONN_RUNTIME_INSTALL_PATH ("");
    const char* const MAVCONN_MEDIA_INSTALL_PATH   ("");
    /* Config and Log path might be relative because they could be user and therefore runtime dependent */
    const char* const MAVCONN_CONFIG_INSTALL_PATH  ("");
    const char* const MAVCONN_LOG_INSTALL_PATH     ("");
    const char* const MAVCONN_CAPTURE_INSTALL_PATH ("");

#ifdef CMAKE_CONFIGURATION_TYPES
    const char* const MAVCONN_MEDIA_DEV_PATH      ("/home/pixhawk/pixhawk/mavconn/light-release/media/"  MACRO_QUOTEME(CMAKE_BUILD_TYPE));
    const char* const MAVCONN_CONFIG_DEV_PATH     ("/home/pixhawk/pixhawk/mavconn/light-release/config/" MACRO_QUOTEME(CMAKE_BUILD_TYPE));
    const char* const MAVCONN_LOG_DEV_PATH        ("/home/pixhawk/pixhawk/mavconn/light-release/log/"    MACRO_QUOTEME(CMAKE_BUILD_TYPE));
    const char* const MAVCONN_CAPTURE_DEV_PATH    ("/home/pixhawk/pixhawk/mavconn/light-release/capture/"MACRO_QUOTEME(CMAKE_BUILD_TYPE));
#else
    const char* const MAVCONN_MEDIA_DEV_PATH      ("/home/pixhawk/pixhawk/mavconn/light-release/media");
    const char* const MAVCONN_CONFIG_DEV_PATH     ("/home/pixhawk/pixhawk/mavconn/light-release/config");
    const char* const MAVCONN_LOG_DEV_PATH        ("/home/pixhawk/pixhawk/mavconn/light-release/log");
    const char* const MAVCONN_CAPTURE_DEV_PATH    ("/home/pixhawk/pixhawk/mavconn/light-release/capture");
#endif
}

#endif /* _MAVCONNPathConfig_H__ */
